//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOdev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public string KitapAdi { get; set; }
        public string Yazar { get; set; }
        public string Baski { get; set; }
        public string Fiyat { get; set; }
        public string Stok { get; set; }
        public int Id { get; set; }
    }
}
